# Generated by Django 4.2.13 on 2024-07-02 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pwa_webpush', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninfo',
            name='user_agent',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='pushmessage',
            name='send_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pushmessage',
            name='title',
            field=models.CharField(default='Message from Demostar.', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='endpoint',
            field=models.URLField(max_length=500),
        ),
    ]
